I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 13, in script
    define kaget = Character("kaget", image = torasumaji_suprisedface)
  File "game/script.rpy", line 13, in <module>
    define kaget = Character("kaget", image = torasumaji_suprisedface)
NameError: name 'torasumaji_suprisedface' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 13, in script
    define kaget = Character("kaget", image = torasumaji_suprisedface)
  File "D:\APK FILES\renpy-8.1.1-sdk\renpy-8.1.1-sdk\renpy\ast.py", line 2508, in execute
    self.set()
  File "D:\APK FILES\renpy-8.1.1-sdk\renpy-8.1.1-sdk\renpy\ast.py", line 2522, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "D:\APK FILES\renpy-8.1.1-sdk\renpy-8.1.1-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 13, in <module>
    define kaget = Character("kaget", image = torasumaji_suprisedface)
NameError: name 'torasumaji_suprisedface' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.1.23060707
 1.0
Thu Nov 30 22:08:53 2023
